rockets/keppler_products/config/routes.rb
KepplerProducts::Engine.routes.draw do
  namespace :admin do
    scope :products, as: :products do
      resources :designs do
        post '/sort', action: :sort, on: :collection
        get '(page/:page)', action: :index, on: :collection, as: ''
        get '/clone', action: 'clone'
        post '/upload', action: 'upload', as: :upload
        get '/reload', action: :reload, on: :collection
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection
      end

      resources :catalogues do
        post '/sort', action: :sort, on: :collection
        get '(page/:page)', action: :index, on: :collection, as: ''
        get '/clone', action: 'clone'
        post '/upload', action: 'upload', as: :upload
        get '/reload', action: :reload, on: :collection
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection
      end

      resources :cotizations do
        post '/sort', action: :sort, on: :collection
        get '(page/:page)', action: :index, on: :collection, as: ''
        get '/clone', action: 'clone'
        post '/upload', action: 'upload', as: :upload
        get '/reload', action: :reload, on: :collection
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection
      end

      resources :products do
        post '/sort', action: :sort, on: :collection
        get '(page/:page)', action: :index, on: :collection, as: ''
        get '/clone', action: 'clone'
        post '/upload', action: 'upload', as: :upload
        post '/select_categories', action: 'select_categories', as: :select_categories
        get '/reload', action: :reload, on: :collection
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection
      end

      resources :categories do
        post '/sort', action: :sort, on: :collection
        get '(page/:page)', action: :index, on: :collection, as: ''
        get '/clone', action: 'clone'
        post '/upload', action: 'upload', as: :upload
        get '/reload', action: :reload, on: :collection
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection
      end

    end
  end
end

rockets/keppler_products/app/models/keppler_products/design.rb
# frozen_string_literal: true

module KepplerProducts
  # Design Model
  class Design < ApplicationRecord
    include ActivityHistory
    include CloneRecord
    include Uploadable
    include Downloadable
    include Sortable
    include Searchable
    acts_as_list
    acts_as_paranoid

    def self.index_attributes
      %i[url]
    end
  end
end

rockets/keppler_products/app/controllers/keppler_products/admin/designs_controller.rb
# frozen_string_literal: true

require_dependency "keppler_products/application_controller"
module KepplerProducts
  module Admin
    # DesignsController
    class DesignsController < ::Admin::AdminController
      layout 'keppler_products/admin/layouts/application'
      before_action :set_design, only: %i[show edit update destroy]
      before_action :index_variables
      include ObjectQuery

      # GET /products
      def index
        respond_to_formats(@designs)
        redirect_to_index(@objects)
      end

      # GET /products/1
      def show; end

      # GET /products/new
      def new
        @design = Design.new
      end

      # GET /products/1/edit
      def edit; end

      # POST /products
      def create
        @design = Design.new(design_params)

        if @design.save
          redirect(@design, params)
        else
          render :new
        end
      end

      # PATCH/PUT /products/1
      def update
        if @design.update(design_params)
          redirect(@design, params)
        else
          render :edit
        end
      end

      def clone
        @design = Design.clone_record params[:design_id]
        @design.save
        redirect_to_index(@objects)
      end

      # DELETE /products/1
      def destroy
        @design.destroy
        redirect_to_index(@objects)
      end

      def destroy_multiple
        Design.destroy redefine_ids(params[:multiple_ids])
        redirect_to_index(@objects)
      end

      def upload
        Design.upload(params[:file])
        redirect_to_index(@objects)
      end

      def reload; end

      def sort
        Design.sorter(params[:row])
      end

      private

      def index_variables
        @q = Design.ransack(params[:q])
        @designs = @q.result(distinct: true)
        @objects = @designs.page(@current_page).order(position: :asc)
        @total = @designs.size
        @attributes = Design.index_attributes
      end

      # Use callbacks to share common setup or constraints between actions.
      def set_design
        @design = Design.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def design_params
        params.require(:design).permit(
          :url
        )
      end
    end
  end
end

rockets/keppler_products/app/views/keppler_products/admin/designs/_description.haml
%aside.control-sidebar.control-sidebar-light
  .tab-content
    %p.control-sidebar-heading
      = @activities.empty? ? t('keppler.messages.no_events') : t("keppler.titles.history")
    %ul.timeline
      - @activities.each do |activity|
        - if activity.trackable_type.eql? "Session"
          %li
            = render partial: "public_activity/session/#{activity.key.split(".").second}", locals: { activity: activity, method: "id" }
        - else
          %li
            = render partial: "public_activity/layout/#{activity.key.split(".").second}", locals: { activity: activity, method: "id" }
.control-sidebar-bg

rockets/keppler_products/app/views/keppler_products/admin/designs/_form.haml
= simple_form_for [:admin, :products, @design] do |f|
  .container
    .row
      .col-lg-2
        = link_to admin_products_designs_path, 'data-position': 'bottom', 'data-tooltip': t('keppler.actions.back') do
          .arrow-back.btn.btn-default
            %i.fa.fa-angle-left
            = t('keppler.actions.back')

    .row
      .col-lg-12
        .box.slice-box
          .box-header.with-border
            %h3.box-title= t('keppler.models.pluralize.designs').humanize
            .box-tools.pull-right
              %a.btn.btn-box-tool{'data-widget': 'collapse', type: 'button'}
                %i.fa.fa-minus
          .box-body
            %table.table.table-bordered
              %tbody
                .form-padding
                  .col-xs-12
                    = f.input :url, as: :string
                  .col-xs-12
                    .pull-right
                      = f.button :submit, t('keppler.actions.save'), name: '_save', class: 'btn-primary'
                      = f.button :submit, t('keppler.actions.save_and_add_another'), name: '_add_other'

rockets/keppler_products/app/views/keppler_products/admin/designs/_listing.haml
- objects.each do |object|
  %tr{ id: "row-#{object.id}" }
    %td.item-check{ style: 'width: 10%' }
      - if can?(model).destroy_multiple?
        .checkbox
          %label{ for: "checkbox-#{object.id}" }
            %input{ type: 'checkbox', id: "checkbox-#{object.id}", 'checklist-model' => 'check', 'checklist-value' => "#{object.id}", '@click' => "listDelete(#{object.id})"}
            %span.cr
              %i.cr-icon.glyphicon.glyphicon-ok
    - attributes.each do |attribute|
      - if @attachments.dig('images', 'names').include?(attribute.to_s)
        %td
          = link_to({ action: :show, id: object.id, search: @query }, { class: 'show-row' }) do
            %span
              = image_tag object.try(attribute).url if object.try(attribute).url
      - elsif @attachments.dig('images', 'names').map(&:pluralize).include?(attribute.to_s)
        %td
          = link_to({ action: :show, id: object.id, search: @query }, { class: 'show-row' }) do
            %span
              - object.try(attribute).each do |image|
                = image_tag image.try(:url)
      - elsif object.try(attribute).is_a?(Integer)
        %td
          = link_to({ action: :show, id: object.id, search: @query }, { class: 'show-row' }) do
            %span= object.try(attribute)
      - else
        %td
          = link_to({ action: :show, id: object.id, search: @query }, { class: 'show-row' }) do
            %span= object.try(attribute).try(:truncate_words, 4)

    %td.dropdown{ style: 'width: 15px;padding-right:15px;' }
      %a.action-btn.pull-right{:id => "menu-#{object.id}", 'aria-expanded': 'false', 'aria-haspopup': 'true', 'data-toggle': 'dropdown' }
        %i.icon-options-vertical
      %ul.actions.dropdown-menu{ 'aria-labelledby': "menu-#{object.id}" }
        - if can?(model).index?
          %li
            = link_to({action: :show, id: object}, {title: t('keppler.actions.show')}) do
              %i.icon-eye
              = t('keppler.actions.show')
        - if can?(model).update?
          %li
            = link_to({action: :edit, id: object}, {title: t('keppler.actions.edit')}) do
              %i.icon-pencil
              = t('keppler.actions.edit')
        - if can?(model).clone?
          %li
            = link_to(admin_products_design_clone_path(object), {title: t('keppler.actions.clone')}) do
              %i.icon-docs
              = t('keppler.actions.clone')
        - if can?(model).destroy?
          %li
            = link_to({action: :destroy, id: object}, {title: t('keppler.actions.delete'), method: :delete, data: { confirm: t('keppler.messages.data_confirm') }}) do
              %i.icon-trash
              = t('keppler.actions.delete')

    %td{ style: 'width: 5%;'}
      %a.drop{ href: '#' }
        %i.icon-cursor-move

rockets/keppler_products/app/views/keppler_products/admin/designs/edit.haml
= render 'form'

rockets/keppler_products/app/views/keppler_products/admin/designs/index.haml
#index-container{ controller: 'designs' }
  .container
    .row
      .listing.col-lg-12.col-xs-12
        %section.content-header.index-header
          %h1
            = t("keppler.models.pluralize.designs").humanize
          = entries(@total, @objects)
        %section.content-actions
          .toolbar
            .toolbar-item
              = link_to reload_admin_products_designs_path, class: 'tool-btn', remote: true, title: t('keppler.actions.reload_page') do
                %i.icon-reload
            - if can?(model).download?
              %li.toolbar-item.dropdown
                %a.dropdown-toggle{ 'data-toggle': 'dropdown', href: '#', title: t('keppler.actions.download_records') }
                  %i.icon-cloud-download
                %ul.dropdown-menu
                  %li= link_to t('keppler.actions.download.csv'), admin_products_designs_path(format: :csv), class: 'tool-btn'
                  %li= link_to t('keppler.actions.download.xls'), admin_products_designs_path(format: :xls), class: 'tool-btn'
            - if can?(model).upload?
              .toolbar-item
                = link_to '#', class: 'tool-btn', title: t('keppler.actions.upload_records'), id: 'upload' do
                  %i.icon-cloud-upload
            .toolbar-item
              %a.tool-btn{ 'data-confirm': t('keppler.messages.data_confirm'), 'data-method': 'delete', 'v-bind:href': 'link', rel: 'nofollow', ':class': '{disabled: !checks}' }
                %i.icon-trash
          - if can?(model).create?
            .add
              = link_to new_admin_products_design_path, class: 'btn-add' do
                +
                = t('keppler.actions.add')
          .hide
            = form_tag admin_products_design_upload_path(@objects), id: 'upload-form', multipart: true, method: :post do
              = file_field_tag :file, id: 'upload-file'

        .box.slice-box
          .box-body.no-padding
            %table.table
              %thead
                - if @objects.size.zero?
                  %tr
                    %th.not-records.center
                      %h6= t('keppler.messages.not_found_records', model: t('keppler.models.pluralize.designs'))

                - else
                  %tr
                    %th
                      - if can?(model).destroy_multiple?
                        .item-check
                          .checkbox
                            %label{ for: 'checkbox-all' }
                              %input{ type: 'checkbox', id: 'checkbox-all', '@click': 'selectAll()' }
                              %span.cr
                                %i.cr-icon.glyphicon.glyphicon-ok
                    - @attributes.each do |attribute|
                      %th
                        = sort_link(@q, attribute) do
                          = t("activerecord.attributes.#{attribute.to_s}")
                    %th
                    %th

              %tbody.objects-container{ 'data-update-url': sort_admin_products_designs_path }
                = render 'admin/layouts/listing_preloader'
                = render 'listing', objects: @objects, query: @query, attributes: @attributes

        %center.paginator-module
          = paginate @objects, window: 1
  .listing-show
    = render 'description', activities: @activities

rockets/keppler_products/app/views/keppler_products/admin/designs/new.haml
= render 'form'

rockets/keppler_products/app/views/keppler_products/admin/designs/reload.js.haml
$('.objects-container').html("#{j render 'listing', objects: @objects}");
$('.objects-container').css('opacity', '0');
$('.spinner2').css('display', 'block');
var request = $.ajax({url: "/admin/designs", method: "get", dataType: "html"});
request.done(function(msg){$('.spinner2').css('display', 'none');$('.objects-container').css('opacity', '1');});

rockets/keppler_products/app/views/keppler_products/admin/designs/show.haml
.container
  .row
    .col-lg-2
      = link_to admin_products_designs_path, 'data-position': 'bottom', 'data-tooltip': t('keppler.actions.back') do
        .arrow-back.btn.btn-default
          %i.icon-arrow-left
          = t('keppler.actions.back')
  .show-section
    .row
      .col-lg-12
        .box.slice-box.p-15
          .box-header.with-border
            %h3.box-title= t('keppler.models.singularize.design').humanize
            .box-tools.pull-right
              - if can?(model).update?
                = link_to edit_admin_products_design_path(@design), class: 'btn btn-box-tool', title: t('keppler.actions.edit') do
                  %i.icon-pencil
              - if can?(model).destroy?
                = link_to admin_products_design_path(@design), class: 'btn btn-box-tool', title: t('keppler.actions.delete'), method: :delete, data: { confirm: t('keppler.messages.data_confirm') } do
                  %i.icon-trash

          .box-body.no-padding
            %table.table
              %tbody
                - @design.as_json(except: %w[position deleted_at]).each do |attribute, value|
                  %tr.list-row
                    %th.display-label= t("activerecord.attributes.#{attribute}")
                    %td.display-value.fs-body-1.tc-black-2
                      - if @attachments.dig('images', 'names').include?(attribute)
                        = image_tag value.url if value.url
                      - elsif @attachments.dig('images', 'names').map(&:pluralize).include?(attribute)
                        - value.each do |image|
                          = image_tag image.url if image.url
                      - else 
                        = sanitize raw value